INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Canada');
INSERT INTO category (description) VALUES ('Mexico');
INSERT INTO category (description) VALUES ('China');
INSERT INTO unit_of_measure (uom) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (uom) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (uom) VALUES ('Cup');
INSERT INTO unit_of_measure (uom) VALUES ('Pinch');
INSERT INTO unit_of_measure (uom) VALUES ('Ounce');